### ISSUE TITLE
TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block

### ISSUE THREAD

**Issue by tommym9** [drud/ddev-contrib#146]
Hi,

I've bumped into this issue when adding a new index to elasticsearch (Drupal 8 site). After a bit of digging it looks like Elasticsearch is hitting or getting towards its memory limit.

I did clock there is a note in the readme of this project about increasing the memory limit, but no instructions on how to do this. My docker knowledge isn't the greatest so I've been playing with my `docker-compose.elasticsearch.yaml` in the hopes I can get it working. No joy so far.

Here is my file for reference:

```
version: '3.6'
services:
  elasticsearch:
    container_name: ddev-${DDEV_SITENAME}-elasticsearch
    hostname: ${DDEV_SITENAME}-elasticsearch
    image: elasticsearch:7.9.3
    ports:
      - "9200"
      - "9300"
    environment:
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTP_EXPOSE=9200:9200
      - HTTPS_EXPOSE=9201:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
      - ".:/mnt/ddev_config"
  web:
    links:
      - elasticsearch:elasticsearch

volumes:
  elasticsearch:

```

On my docker desktop I've got the memory up at 16gb so it shouldn't touch that.

Any help would be massively appreciated!

Cheers

Tom

The full error I'm seeing can be found here:
`{"error":{"root_cause":[{"type":"cluster_block_exception","reason":"index [elasticsearch_index_db_news] blocked by: [TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block];"}],"type":"cluster_block_exception","reason":"index [elasticsearch_index_db_news] blocked by: [TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block];"},"status":429} `

And running `ddev logs -s elasticsearch` gives me:
`{"type": "server", "timestamp": "2021-07-15T14:16:25,257Z", "level": "WARN", "component": "o.e.c.r.a.DiskThresholdMonitor", "cluster.name": "docker-cluster", "node.name": "REDACTED-drupal-elasticsearch", "message": "flood stage disk watermark [95%] exceeded on [jpkE4gtsRfG26M27cBaP4g][REDACTED-drupal-elasticsearch][/usr/share/elasticsearch/data/nodes/0] free: 3.2gb[3.1%], all indices on this node will be marked read-only", "cluster.uuid": "mOTWzkOWSIK-2dyYJLV-4A", "node.id": "jpkE4gtsRfG26M27cBaP4g"  }`
