### ISSUE TITLE
BUG: Failed to run pgsql_export

### ISSUE THREAD

**Issue by tyler36** [drud/ddev-contrib#153]
I was updating my postgres image to match my server environment and when I noticed that `ddev pgsql_export` didn't work.

```
$ ddev pgsql_export
bash: /mnt/ddev_config/import-db/postgresql.db.sql: Permission denied
Failed to run pgsql_export : exit status 
```

I though I might have messed something up. So I
- deleted images 
  ```
  ddev stop
  ddev delete -O -y
  ```

- changed `docker-compose.postgres.yaml`

  ```yaml
      image: mdillon/postgis:11
  ```

But recieved the same message. 

I tried removing `./.ddev/import-db`, creating it in WSL2 and running the command.
I tried removing `./.ddev/import-db` and letting DDEV create the directory; both without success

I noticed PR #152  and tried changing the image to `postgres:13.4`, but without success.

I also tried using the `ddev snapshot` but it didn't work (it only target MySQL right?) . It would be nice if DDEV used my preferred database for snapshot. 😄 

OS: WSL2 on Win10
DDEV: v1.18.0-rc1-9-gac148660

**Comment by dacostafilipe** [comment]
Sounds like the `import-db` folder is missing in `.ddev`

**Comment by tyler36** [comment]
Sorry, it does not work.

### Setup
- Install laravel

```bash
$ laravel new ddev-postgres
$ php artisan --version
Laravel Framework 8.61.0
```

- Install DDEV, accept defaults

```bash
$ ddev config
$ ddev --version
ddev version v1.17.7
```

- Copy `docker-compose.postgres.yaml` to `.ddev`
- Copy `commands/postgres` directory to your project's `.ddev/commands`

- Update `.env`

```env
DB_CONNECTION=pgsql
DB_HOST=postgres
DB_PORT=5432
DB_DATABASE=db
DB_USERNAME=db
DB_PASSWORD=db
```

- Attempt to migrate database

```bash
$ ddev artisan migrate:fresh
...
Migration table created successfully.
```

- This confirms that Laravel has been successfully setup to use Postgres via DDEV.
- Note: There is no `.ddev/import-db` folder present. Current installation has no mention of creating one.

- Run `ddev pgsql_export`

```bash
$ ddev pgsql_export
bash: /mnt/ddev_config/import-db/postgresql.db.sql: Permission denied
Failed to run pgsql_export : exit status 1
```

- Note: There is now a `.ddev/import-db` folder present, created by the `pgsql_export`.
```bash
$ ls -la ./.ddev
drwxr-xr-x 14 dev       dev       4096 Sep 27 10:00 .
...
drwxr-xr-x  2 root      root      4096 Sep 27 10:00 import-db
```

> Sounds like the import-db folder is missing in .ddev or has missing permissions.
The docs make no mention of creating a `import-db` folder. As stated in the original post, it doesn't seem to matter. But let's try it again.

- Delete `.ddev/import-db`
```bash
rm -rf ./.ddev/import-db
```

- Create `.ddev/import-db`
```bash
mkdir ./.ddev/import-db
```

- Attempt to export DB
```bash
$ ddev pgsql_export       
bash: /mnt/ddev_config/import-db/postgresql.db.sql: Permission denied
Failed to run pgsql_export : exit status 1

$ ls -la ./.ddev 
...
drwxr-xr-x  2  dev     dev     4096 Sep 27 10:14 import-db
```

I downgraded DDEV to a stable version. 

OS: WSL2 on Win10
DDEV:  v1.17.7

**Comment by rfay** [comment]
Thanks for the detailed repro! 

Could you please `ddev exec -s postgres 'id -a && ls -l /mnt/ddev-config'`

**Comment by tyler36** [comment]
```bash
$ ddev exec -s postgres 'id -a && ls -l /mnt/ddev-config'
uid=0(root) gid=0(root) groups=0(root)
ls: cannot access '/mnt/ddev-config': No such file or directory
Failed to execute command id -a && ls -l /mnt/ddev-config: exit status 2
```

**Comment by rfay** [comment]
OK, I mistook my _ for -. The requested command should have been `ddev exec -s postgres 'id -a && ls -l /mnt/ddev_config'` 

The standard Postgres recipe mounts ddev-config, perhaps you're not using the one from https://github.com/drud/ddev-contrib/tree/master/docker-compose-services/postgres ?

```yaml
    volumes:
      - type: "volume"
        source: postgres
        target: "/var/lib/postgresql/data"
        volume:
          nocopy: true
      - type: "bind"
        source: "."
        target: "/mnt/ddev_config"
      - ddev-global-cache:/mnt/ddev-global-cache
```

Note that you can just `ddev ssh -s postgres` and look around. `cd /mnt/ddev_config`. `ls -l`. etc.

**Comment by tyler36** [comment]
```
$ ddev exec -s postgres 'id -a && ls -l /mnt/ddev_config'

uid=0(root) gid=0(root) groups=0(root)
total 44
drwxr-xr-x 2 1000 1000 4096 Sep 27 00:36 apache
drwxr-xr-x 7 1000 1000 4096 Sep 27 00:47 commands
-rw-r--r-- 1 1000 1000 7000 Sep 27 00:31 config.yaml
drwxr-xr-x 2 1000 1000 4096 Sep 27 00:31 db-build
-rw-r--r-- 1 1000 1000  669 Aug 31 22:27 docker-compose.postgres.yaml
drwxr-xr-x 2 1000 1000 4096 Sep 27 00:35 homeadditions
drwxr-xr-x 2 root root 4096 Sep 27 01:38 import-db
drwxr-xr-x 2 1000 1000 4096 Sep 27 00:36 nginx_full
drwxr-xr-x 2 1000 1000 4096 Sep 27 00:35 providers
drwxr-xr-x 2 1000 1000 4096 Sep 27 00:31 web-build
```

My comment earlier today is a new project for debugging this issue. I download this repo's zip 2 hours ago and used thoses files with out modification. Here is the `docker-compose.postgres.yaml` from the project.
```yml
version: '3.6'
services:
  postgres:
    container_name: ddev-${DDEV_SITENAME}-postgres
    image: mdillon/postgis:11
    ports:
      - 32784:5432
    environment:
      - POSTGRES_PASSWORD=db
      - POSTGRES_USER=db
      - POSTGRES_DB=db
    volumes:
      - type: "volume"
        source: postgres
        target: "/var/lib/postgresql/data"
        volume:
          nocopy: true
      - type: "bind"
        source: "."
        target: "/mnt/ddev_config"
      - ddev-global-cache:/mnt/ddev-global-cache
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
  web:
    links:
      - postgres:postgres

volumes:
  postgres:
```

Debug repo: https://github.com/tyler36/ddev-posgres
