### ISSUE TITLE
Help to setup FTP service

### ISSUE THREAD

**Issue by nessunluogo** [drud/ddev-contrib#76]
I'm running a project which requires ftp access across multiple vhosts.

I accomplished multi-domain using **additional_hostnames** in `config.yaml` and managed different docroots using a custom `apache/apache-site.conf` file.

Now I'm stuck. I have not enough docker knowledge to add a FTP service.
I'm going to add a `.ddev/docker-compose.ftp.yaml` file but don't know how make it work [vimagick/pure-ftpd](https://hub.docker.com/r/vimagick/pure-ftpd) (or some other).

This is my actual file:
```
version: '3.6'

services:
  pure-ftpd:
    container_name: ddev-${DDEV_SITENAME}-ftp
    image: vimagick/pure-ftpd
    hostname: ftp-dam
    volumes:
      - ./media:/home/ftpuser:rw
    privileged: true
    restart: always
```

ddev starts correctly but don't know how to access the FTP.

Can someone help me?

Thx

**Comment by rfay** [comment]
Maybe you can say why you want ftpd and what you're going to do with it? ftp is pretty much a completely obsolete protocol.  You want to access an ftp server within your project? From where? What's the purpose?

**Comment by nessunluogo** [comment]
@rfay thank you for the answer. I know the issues which come with FTP, but this is something I can't change on the project. Anyway I think this solution can be useful for someone else.

FTP is used to access and upload media files on a remote repository. This is also accessible by other users and other environments so I can't force to replace it with something newer.

For developement purposes I want to replicate the FTP repo in my ddev environment. That's all.

I'm going to explore the additional service solution and I'll add here any progress.

**Comment by rfay** [comment]
So you want to have a container which imitates your remote repository?  Or you want some client to be able to upload files via ftp to your webserver?

Can you just use the remote repository?

Do you need an ftp server or just an ftp client?

**Comment by rfay** [comment]
I *think* you might be asking for something very similar to adding sshd into the web container, but not sure. But you might want to look at the very simple solution for that in https://github.com/drud/ddev-contrib/tree/master/recipes/sshd

**Comment by nessunluogo** [comment]
I need a ftp server and sadly sshd is not an alternative.

In my webserver I have multiple "applications". All applications but one has the same docroot. The other works as a extremely basic DAM (Digital Assets Management).

The DAM is read only via web and can be written via FTP, both from applications (via PHP FTP functions) and external clients. I dont' care about other clients, since I'm just working on "applications". I know it's a bad solution, but right now I can't change it.

At last I made a working ftp service, by adding environment variables used by pure-ftpd.

I share it if it can be useful to someone else:
File: `.ddev/docker-compose.ftp.yaml`
```
version: '3.6'

services:
  ftpd-server:
    container_name: ddev-${DDEV_SITENAME}-ftp
    image: stilliard/pure-ftpd:hardened
    hostname: ftp-dam
    volumes:
      - ../ftp:/home/ftpuser
    privileged: true
    restart: always
    environment:
      PUBLICHOST: "0.0.0.0"
      FTP_USER_NAME: "ftpuser"
      FTP_USER_PASS: "ftpuser"
      FTP_USER_HOME: "/home/ftpuser"
```

Client can connect using this parameters:
* host: ftpd-server
* username: ftpuser
* password: ftpuser

Local folder `ftp` is mapped as `/home/ftpuser` which is set as home folder for the **ftpuser** user
